package org.mate.exploration.genetic.chromosome_factory;

/**
 * The currently supported chromosome factories in combination with genetic algorithms.
 */
public enum ChromosomeFactory {

    ANDROID_RANDOM_CHROMOSOME_FACTORY,
    ANDROID_SUITE_RANDOM_CHROMOSOME_FACTORY,
    HEURISTICAL_CHROMOSOME_FACTORY,
    PRIMITIVE_ANDROID_RANDOM_CHROMOSOME_FACTORY,
    INTENT_ANDROID_RANDOM_CHROMOSOME_FACTORY,
    SAPIENZ_RANDOM_CHROMOSOME_FACTORY,
    SAPIENZ_SUITE_RANDOM_CHROMOSOME_FACTORY,
    BIT_SEQUENCE_CHROMOSOME_FACTORY,
    INTEGER_SEQUENCE_CHROMOSOME_FACTORY,
    ESPRESSO_RANDOM_CHROMOSOME_FACTORY;
}
