package org.mate.utils.testcase;

public enum OptimisationStrategy {
    NO_OPTIMISATION,
    REMOVE_ALL_INTENT_ACTIONS,
    REMOVE_ALL_EXCEPT_LAST_ACTION,
    REMOVE_ALL_ACTIONS_BEFORE_LAST_ACTIVITY_TRANSITION,
    REMOVE_ALL_NON_ACTIVITY_RELATED_ACTIONS,
    REMOVE_ALL_UI_ACTIONS;
}
