package org.mate.accessibility.check.bbc;

public enum AccessibilityViolationType {

    EDITABLE_CONTENT_DESC("EDITABLE_CONTENT_DESC"),
    MISSING_FORM_CONTROL_LABEL("MISSING_FORM_CONTROL_LABEL"),
    MISSING_ALTERNATIVE_TEXT("MISSING_ALTERNATIVE_TEXT"),
    LOW_CONTRAST_RATIO("LOW_CONTRAST_RATIO"),
    SMALL_TOUCH_AREA("SMALL_TOUCH_AREA"),
    DUPLICATE_CONTENT_DESCRIPTION("DUPLICATE_CONTENT_DESCRIPTION"),
    NON_CLICKABLE_SPAN("NON_CLICKABLE_SPAN"),
    MISSING_INPUT_TYPE("MISSING_INPUT_TYPE"),
    LABEL_NOT_DEFINED("LABEL_NOT_DEFINED"),
    LABEL_FAR_FROM_INPUTTEXT("LABEL_FAR_FROM_INPUTTEXT"),
    COLOUR_MEANING("COLOUR_MEANING"),
    SPACING("SPACING"),
    HIDDEN_DECORATIVE_CONTENT("HIDDEN_DECORATIVE_CONTENT"),
    DESCRIPTIVE_LINKS("DESCRIPTIVE_LINKS"),
    VISIBLE_FOCUS("VISIBLE_FOCUS"),
    MANAGING_FOCUS("MANAGING_FOCUS"),
    RADIOGROUPCHECK("RADIOGROUPCHECK"),
    ACTIONABLE_ELEMENTS("ACTIONABLE_ELEMENTS"),
    LINK_TO_ALTERNATIVE_FORMAT("LINK_TO_ALTERNATIVE_FORMAT"),
    PHANTOM_ELEMENT("PHANTOM_ELEMENT"),
    ERROR_MESSAGE("ERROR_MESSAGE");

    private String type;

    private AccessibilityViolationType(String type){
        this.type = type;
    }

    public String getValue(){
        return this.type;
    }

}
